server:
  port: 8080

spring:
  datasource:
    name: haokes
    url: jdbc:mysql://39.96.209.215:3306/haoke
    username: yangzixin
    password: yangyang0.0
    #driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.haoke.yang.bean  # 注意：对应实体类的路径
